services:
  backend:
    build: ./
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=8080
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`test.test.mortarbulksms.com`)
      - traefik.docker.network=fastapi-public
    networks:
      -fastapi-public

networks:
  fastapi-public:
    external: true

