services:
  backend:
    build: ./
    restart: always
    labels:
      traefik.docker.network: traefik-public
      traefik.enable: "true"
      traefik.http.routers.api-http.entrypoints: http
      traefik.http.routers.api-http.middlewares: https-redirect
      traefik.http.routers.api-http.rule: Host(`test.mortarbulksms.com`)
      traefik.http.routers.api-https.tls: "true"
      traefik.http.routers.api-https.tls.certresolver: le
      traefik.http.services.api.loadbalancer.server.port: "8080"
  networks:
    traefik-public: null

networks:
  traefik-public:
    name: traefik-public
    external: true

